### ISSUE TITLE
No compiled .elf available

### ISSUE THREAD

**Issue by korgano** [xerpi/libds4ps2#1]
Having a compiled libds4ps2.elf would help people who want to use a DS4 on their PS2, but don't know how to compile a .elf file or have problems with the software. Also, it would be less confusing to all the people who read the "DS4 on PS2" articles and wind up stuck in the sample .elf, since that's the only .elf available.

**Comment by xerpi** [comment]
The problem is that libds4ps2 is currently useful only for PS2 developers. The library is intended to be used and linked with Homebrew. The only way to get it working with the PS2 games would be doing some nasty hacks to the Open PS2 Loader for example, which I would like to do.

**Comment by exmex** [comment]
Is this still the case? I mean that it's only useful for PS2 developers?

**Comment by xerpi** [comment]
Yes it is only for developers. I'd like somebody to help me implement it to Open PS2 Loader for example, but it seems that OPL devs are not interested in that :/

**Comment by exmex** [comment]
Hm. That's a shame. I hate the nobs of the PS2 controller. But thanks for the quick answer ;)

**Comment by carlosporta** [comment]
Is it still only useful for developers? =(

**Comment by xerpi** [comment]
Yeah, probably the best idea would be to modify Open PS2 Loader to load a custom libpad.irx using this library when loading games.

**Comment by laraeb** [comment]
Hey Xerpi,

I was wondering if you made any progress with having the ds3ps2.irx functioning with ps2 games.

**Comment by xerpi** [comment]
@laraeb https://github.com/ifcaro/Open-PS2-Loader already has support for it and more.
